services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=basketball_service'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - '5432:5432'

  basketball-service:
#    image: basketball-service:latest
    build:
      dockerfile: ./Dockerfile
      context: ./demo
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/basketball_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
